name: Main

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Running
      run: |
        pip3 install --no-cache-dir -U -r req.txt
        python3 copy_all.py
