name: Main
on:
  schedule:
  - cron: "* * * * *"
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Running
      run: |
        echo "Running!"
