name: Main
on:
  schedule:
  - cron: "30 * * * *"
  workflow_dispatch:

env:
  HELLO: "hello"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Running
      run: |
        echo "Running!"
